services:
  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: furia-bot
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - mongo
    restart: unless-stopped
    environment:
      - CHROME_BIN=/usr/bin/chromium
      - PATH=/usr/lib/chromium:$PATH

  mongo:
    image: mongo:latest
    container_name: furia-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
