name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version (if release)
        id: vars
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "VERSION=latest" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          docker build -f docker/Dockerfile -t $IMAGE_NAME:${{ env.VERSION }} .

      - name: Push Docker image
        if: github.event_name != 'pull_request'
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}

          # Push the version tag
          docker push $IMAGE_NAME:${{ env.VERSION }}

          # Also tag and push latest if this is a release
          if [ "${{ env.VERSION }}" != "latest" ]; then
            docker tag $IMAGE_NAME:${{ env.VERSION }} $IMAGE_NAME:latest
            docker push $IMAGE_NAME:latest
          fi
